### ISSUE TITLE
[Feature Request] Add blacklist item

### ISSUE THREAD

**Issue by SnowCutieOwO** [Norbit4/PlayerMarket#8]
``` YAML
blacklist:
   - lore-contain: 'Untradable Item'
   - name-contain: '(Untradable)'
   - item-name: bedrock
   - item-name: barrier
```

This would be useful in some survival server if they have some important custom items. :3
